#!/usr/bin/env php
<?php

/**
 * Console mode
 */

define('__ENV__', 'cli');

require 'vendor/autoload.php';

use Craft\Debug\Logger;
use Craft\Box\Mog;
use Craft\Router;
use Craft\App;


/**
 * Config
 */

error_reporting(E_ALL & ~E_NOTICE);
ini_set('error_reporting', E_ALL & ~E_NOTICE);

date_default_timezone_set('UTC');


/**
 * Logger setup
 */

Logger::register(
    new Logger\DailyFile(__DIR__ . '/logs')
);


/**
 * Generate request
 */

$request = App\Request::create();
Mog::request($request);


/**
 * Commands setup
 */

$commands = new Router\Basic([
    'hello'  => 'App\Cli\Hello',
    'deploy' => 'App\Cli\Deploy',
]);

$console = new App\Plugin\Console($commands);


/**
 * Application setup
 */

$app = new App\Kernel($console);


/**
 * Run ! You fools !
 */

$app->handle($request);