#!/usr/bin/env php
<?php

/**
 * Console mode
 */

define('__ENV__', 'cli');

require 'vendor/autoload.php';

use Craft\Debug\Logger;
use Craft\Box\Mog;
use Craft\App\Request;
use Craft\Cli;


/**
 * Error level
 */

error_reporting(E_ALL & ~E_NOTICE);
ini_set('error_reporting', E_ALL & ~E_NOTICE);


/**
 * Generate request
 */

$request = Request::create();
Mog::request($request);


/**
 * Logger setup
 */

Logger::register(
    new Logger\DailyFile(__APP__ . '/logs')
);


/**
 * Application setup
 */

$app = new Cli\App([
    'hello'  => 'App\Console\Hello',
    'deploy' => 'App\Console\Deploy',
]);


/**
 * Run ! You fools !
 */

$app->handle($request);